# Streamlit secrets configuration file
# Place this file in: .streamlit/secrets.toml
# Make sure to add .streamlit/ to your .gitignore file

# API Keys
[api_keys]
gemini_api_key = "AIzaSyA-rSLM1cmNnjwQKzgSvG8kAAnFWj-IH4I"


# Other configuration
[app]
environment = "development"
debug = true